---
- name : Installation du serveur web apache2
  hosts: all
  become : yes

  tasks:
    - name: Ensure apache is at the last version
      apt:
        name: apache2
        state: latest

    - name : create document root
      file:
        path: "/var/www/html/"
        state: directory
        owner: "root"
        mode: 0755

    - name: ensure apache2 is running
      service:
        name: apache2
        state: started

