---
- name: My first fact playbook
  hosts: all

  tasks:
    - debug:
        msg: "{{ansible_architecture}}"

    - debug:
        msg: "{{ansible_apparmor.status}}"

    - debug:
        msg: "{{ansible_all_ipv4_addresses}}"

    - debug:
        msg: "{{ansible_env}}"

    - debug:
        msg: "{{ansible_os_family}}"
