---
- name: Looping through a list of variables
  hosts: all
  vars:
    packages:
      - httpd
      - python
      - mysql

  tasks:
    - name: List packages
      debug:
        msg: "{{packages}}}"
        loop: "{{packages}}"

