#Ajouter un utilistaeur avec les propriétiés suivantes:
#-nom : rsergio
#-uid: 1040
#- appartient au groupe des admins
#- Creer une clé SSH 2048-bit pour cet utilisateur dans ~rsergio/.ssh/id_rsa
#
# 
---
- name: Exercice pratique 2, creation d'utilisateur
  hosts: testlab
  tasks:
    - name: Add the user 'rsergio' with a specific uid and add it to 'admins'
      user:
        name: rsergio
        comment: Remi sergio
        uid: 1040
        group: adm
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
      become: yes
