---
- name: My conditional first test
  hosts: all

  tasks:
    - package:
      name: "httpd"
      state: present
      when: ansible_os_family == "RedHat"
    - package:
      name: "apache2"
      state: present
      when: ansible_os_family = "Debian"
