---
- name: Authorithative DNS Server Configuration Playbook
  hosts: all
  become: true
  tasks:
      - name: Setting up the static hosname in the machine
        command: hostnamctl set-hostaname dnsprimary.tesrov.lab

      - name: Install the bind packages in the machine
        dnf:
          name:
            - bind
            - bind-utils
          state: latest

      - name: Making changes in the /etc/named.conf configuration file (Comment listen-on port 53 line )
        replace:
          path: /etc/named.conf
          regexp: 'listen-on port 53 { 127.0.0.1;};'
          replace: '//listen-on port 53 {127.0.0.1;};'

      - name: Making changes in the /etc/namd.conf configuration file (Comment listen-on-v6 port 53 line)
        replace:
          path: /etc/named.conf
          regexp: 'listen-on-v6 port 53 { ::1;};'
          replace: '//listen-on-v6 port 53 { ::1;};'

      - name: Making changes in the /etc/named.conf configuration file. ( Modify allow-query line)
        replace:
          path: /etc/named.conf
          regexp: 'allow-query { localhost; }'
          replace: 'allow-query { localhost; 10.5.43.0/24}'

      - blockinfile:
          path: /etc/named.conf
          inserafter: EOF
          block:
            //forward zone
            zone "tesrov.lab" IN {
              type master;
              file "tesrov.lab.db";
              allow-update {none;};
              allow-query {any;};
            };
           
        - name: Creating forward lookup zone file using ansible template file
          template:
            src: forward.j2
            dest: /var/named/tesrov.lab.db
            owner: named
            group: named

        - name: Creating reverse lookup zone file using ansible template file
          template:
            src: reverse.j2
            dest: /var/named.tesrov.lab.rev
            owner: named
            group: named

        - name: Allowing DNS traffice in the firewall
          firewalld:
            service: dns
            zone: public
            permanent: true
            immediate: true
            state: enabled

        - name: Starting and enabling the DNS service
          service:
            name: named
            state: started
            enabled: yes 
